name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  individual:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.1
    with:
      working_directory: './_example/individual/'
  master:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.1
    with:
      working_directory: './_example/master/'
  member:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.1
    with:
      working_directory: './_example/member/'
