name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  individual:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.7
    with:
      working_directory: './examples/individual/'
  master:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.7
    with:
      working_directory: './examples/master/'
  member:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.7
    with:
      working_directory: './examples/member/'
